package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

// README markers the generated module table is spliced between. Everything
// outside them is hand-written; everything inside is owned by `dzm readme`.
const (
	readmeBegin = "<!-- modules:begin (generated by `dzm readme` — do not edit) -->"
	readmeEnd   = "<!-- modules:end -->"
)

// registryBase is where each module's docs page lives.
const registryBase = "https://doze.nerdmenot.in/registry/doze"

// runReadme regenerates the module table in README.md from the describers map —
// the same source the registry docs and the signed engine-support lists come
// from, so the table can't drift. A test (TestReadmeTableCurrent) fails when
// the committed README is stale.
func runReadme(args []string) error {
	fs := flag.NewFlagSet("readme", flag.ExitOnError)
	path := fs.String("readme", "README.md", "README to update in place")
	_ = fs.Parse(args)

	b, err := os.ReadFile(*path)
	if err != nil {
		return err
	}
	updated, err := spliceReadmeTable(string(b))
	if err != nil {
		return err
	}
	if updated == string(b) {
		fmt.Printf("%s is up to date\n", *path)
		return nil
	}
	if err := os.WriteFile(*path, []byte(updated), 0o644); err != nil {
		return err
	}
	fmt.Printf("updated %s\n", *path)
	return nil
}

// spliceReadmeTable replaces the marker-delimited region of readme with the
// freshly generated table.
func spliceReadmeTable(readme string) (string, error) {
	begin := strings.Index(readme, readmeBegin)
	end := strings.Index(readme, readmeEnd)
	if begin < 0 || end < 0 || end < begin {
		return "", fmt.Errorf("README is missing the %s / %s markers", readmeBegin, readmeEnd)
	}
	return readme[:begin] + readmeBegin + "\n" + moduleTable() + readmeEnd + readme[end+len(readmeEnd):], nil
}

// moduleTable renders the module overview from Describe(): name (linked to the
// registry page), category, supported engine versions, tagline.
func moduleTable() string {
	names := make([]string, 0, len(describers))
	for n := range describers {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("| Module | Category | Engine versions | |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, name := range names {
		d := describers[name].Describe()
		versions := "built-in"
		if len(d.Versions) > 0 {
			versions = strings.Join(d.Versions, " · ")
		}
		fmt.Fprintf(&b, "| [`%s`](%s/%s) | %s | %s | %s |\n",
			name, registryBase, name, d.Category, versions, d.Tagline)
	}
	return b.String()
}
